export const BALANCES_UPDATE = "BALANCES_UPDATE";
export const BALANCES_RESET = "BALANCES_RESET";
export const BALANCE_SELECT = "BALANCE_SELECT";
export const CURRENCY_BALANCES_UPDATE = "CURRENCY_BALANCES_UPDATE";

export const USER_UPDATE = "USER_UPDATE";
export const USER_LOGOUT = "USER_LOGOUT";

export const ROLL_UPDATE = "ROLL_UPDATE";
export const CATEGORY_UPDATE = "CATEGORY_UPDATE";
export const HERO_UPDATE = "HERO_UPDATE";
export const TICKET_UPDATE = "TICKET_UPDATE";
export const APPROVE_UPDATE = "APPROVE_UPDATE";
